# -*- coding: utf-8 -*-
"""Apriori-Association.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzcP8hGl6TUFXcm4S7utB2yA3rTyExzN
"""

pip install apyori

import pandas as pd
from apyori import apriori

lista_mercado = pd.read_csv('/content/mercado (1).csv',header=None)

lista_mercado

transacoes = []
for i in range(len(lista_mercado)):
  transacoes.append([str(lista_mercado.values[i, u]) for u in range(lista_mercado.shape[1])])

transacoes

regra = apriori(transacoes, min_support = 0.3, min_confidence = 0.8, min_lift = 2)
resultado = list(regra)

len(resultado)

L1 = []
L2 = []
suporte = []
confianca = []
lift = []

for resultado in resultados:
  s = resultado[1]
  result_rules = resultado[2]
  for result_rule in result_rules:
    #print(result_rule)
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    d = result_rule[3]
    #print(a, '--', b, '--', c, '--', d)
    L1.append(a)
    L2.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(d)

L1

L2

suporte

confianca

lift

rules_df = pd.DataFrame({'L1': L1, 'L2': L2, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

rules_df